/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.modules.*

fun main() {
    val processor = PrimeNumberProcessor(1..20)
    val result = processor.process()
    result.primes.forEach{it.printValue()}
    println()
    result.odds.forEach{it.printValue()}
    println()
    result.evens.forEach{it.printValue()}
}
